WikiTeam/wikiteam

- tox.ini
Most people know about pep8 which enforce coding style.  pyflakes
goes a step beyond by analyzing the code.
flake8 is basically a wrapper around both pep8 and pyflakes and comes
with some additional checks.  I find it very useful since you only need
to require one package to have a lot of code issues reported to you.
This patch provides a 'flake8' tox environement to easily install
and run the utility on the code base.  One simply has to:
tox -eflake8
The repository in its current state does not pass checks We can later
easily ensure there is no regression by adjusting Travis configuration
to run this env.
The env has NOT been added to the default list of environement.
More informations about flake8: https://pypi.python.org/pypi/flake8
> Add tox env for flake8 linter

- dumpgenerator.py
allow dumpgenerator.py to continue even if image description load fails
> dumpgenerator: catch errors for missing image descriptions

- dumpgenerator.py
List of image file name needs to be converted to Unicode, because images list fetched from wiki is in Unicode.
Otherwise a test a few lines below fails for non-ascii image names:
`if filename2 not in listdir:`
> convert images directory content to unicode when resuming download

- dumpgenerator.py
- testing/test_dumpgenerator.py
This problem was encountered when running
```bash
python dumpgenerator.py --get-wiki-engine http://wiki.openwrt.org
```
The server required an "Accept" HTTP header, which was being removed when setting the user-agent. It works now. Of course, it should be determined whether this behaviour was intentional or not before merging.
This **needs** to be tested before being merged.  It passes all the unit tests, but it might not work in all cases.
> Preserve default headers, fixing openwrt test

- dumpgenerator.py
I forgot that the preceding point only extracts the api.php URL if
the "wiki" argument is passed to say it's a MediaWiki wiki (!).
> Fix API check if only index is passed

- dumpgenerator.py
Needed for http://wiki.crin.org/mediawiki/index.php which returns extra spaces before the XML export output.
> Allow spaces before <mediawiki> tag.

- dumpgenerator.py
Unicode is not supported by hashlib.
http://bugs.python.org/issue2948
> Make filename truncation work with UTF-8

- dumpgenerator.py
* For some reason, in a previous commit I had noticed that maxretries
was not respected in getXMLPageCore, but I didn't fix it. Done now.
* If the "Special" namespace alias doesn't work, fetch the local one.
> Issue #26: Local "Special" namespace, actually limit replies

- dumpgenerator.py
ValueError would not be thrown there. It should have been KeyError.
> Catch KeyError to fix server check

- dumpgenerator.py
We work well without api.php. this was a needless suicide.
Especially as sometimes sysadmins like to disable the API for no
reason and then index.php is our only option to archive the wiki.
> When we have a working index.php, do not require api.php

- .gitattributes
Ignore com extensions, as they were being registered as DCL, which is wrong.
> Fix erroneous linguistics.

- listsofwikis/dokuwiki/dokuinstall.txt
Removed http://www.mirkosertic.de from the list.
> http://www.mirkosertic.de is no longer powered by DokuWiki

- listsofwikis/mediawiki/wikia.py
Note that existence doesn't mean the dump is usable.
> Wikia dumps now use 7z, not gz

- dumpgenerator.py
POST does not follow the redirect from HTTP to HTTPS, which makes the
request (and the entire dump) fail if an API URL is passed like
http://7daystodie-de.gamepedia.com/api.php
Fixes https://github.com/WikiTeam/wikiteam/issues/334
> Use GET rather than POST for allpages API query

- dumpgenerator.py
* It was just an old trick to get past some barriers which were waived with GET.
* It's not conformant and doesn't play well with some redirects.
* Some recent wikis seem to not like it at all, see also issue #311.
> Use GET rather than POST for API requests

- dumpgenerator.py
- wikiteam/mediawiki.py
There are small typos in:
- dumpgenerator.py
- wikiteam/mediawiki.py
Fixes:
- Should read `inconsistencies` rather than `inconsistences`.
- Should read `partially` rather than `partialy`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- dumpgenerator.py
Before, with 50k images in the `images` directory:
```
0 images were found in the directory from a previous session
```
After:
```
53569 images were found in the directory from a previous session
```
---
- Python 2.7.18
- Linux 5.12.8-arch1-1
```
backports.csv==1.0.7
certifi==2020.12.5
chardet==4.0.0
contextlib2==0.6.0.post1
docopt==0.6.2
idna==2.10
internetarchive==2.0.3
jsonpatch==1.32
jsonpointer==2.1
kitchen==1.2.6
mwclient==0.10.1
oauthlib==3.1.0
requests==2.25.1
requests-oauthlib==1.3.0
schema==0.7.4
six==1.16.0
tqdm==4.60.0
urllib3==1.26.4
```
> Fix image resuming

- uploader.py
Currently, `uploader.py` will fail due to permissions if a wikidump has been uploaded previously by another user. This change simply appends the `wikidate` to the identifier to standardize subsequent uploads instead of manual appends of `'-2'` or similar suffixes.
Before:
manual identifier change from `wiki-valorantfandomcom` -> `wiki-valorantfandomcom-2`
After:
unique identifier by dump date `wiki-valorantfandomcom-20220321`
> Add dump date to item identifier

- uploader.py
Forgot to update the IA URL to use the appended identifier if date was appended. Upload works fine without but the displayed URL will be for the previously uploaded item instead.
Before:
identifier `wiki-artofproblemsolvingcom_wiki-20220321` displays `https://archive.org/details/wiki-artofproblemsolvingcom_wiki` upon upload
After:
identifier `wiki-artofproblemsolvingcom_wiki-20220321` displays `https://archive.org/details/wiki-artofproblemsolvingcom_wiki-20220321` upon upload
> Display appended-date IA URL if appended

- dumpgenerator.py
Before, you would get `UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal`. The `%s` versus `{}` change was needed because otherwise you would get `UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)`. There is probably a better way of solving that, but this one does work.
> Work around unicode titles not working with resuming and fix truncation when resuming

- dumpgenerator.py
`session.get` uses our configured User-Agent, while `requests.get` uses the default one. Needed for `python2 -u dumpgenerator.py --xml --xmlrevisions --images https://fidopedia.fido.de/`, as that site rejects the requests user agent.
(That site also requires other stuff; see [this branch](https://github.com/Pokechu22/wikiteam/tree/fidopedia) ([perma](https://github.com/Pokechu22/wikiteam/tree/d43dedb304cb34a75595b8d4c70196488e72357f)), though that's not fully complete.)
> Use `session.get` instead of `requests.get` in `getXMLHeader`

- dumpgenerator.py
Before, the download would die, and need to be resumed from the start.
I ran into it while working on [this](https://archive.org/details/wiki-familysearch.org_en_wiki), which ended up dying on [FamilySearch Wiki:WikiProject England Parish Tables Part 2](https://www.familysearch.org/en/wiki/index.php?title=FamilySearch_Wiki:WikiProject_England_Parish_Tables_Part_2&action=history), which happens to have a deleted revision (apparently [the only deleted revision on a non-deleted page](https://www.familysearch.org/en/wiki/Special:Log?type=delete&user=&page=&wpdate=&tagfilter=&subtype=revision)). I was able to successfully redownload with this patch. (Well, I actually made another change so that it wouldn't restart from the beginning, but instead the project namespace - if I had had to redo …
> Skip empty revisions when using --xmlrevisions

- dumpgenerator.py
This means it uses our configured user-agent, as well as any cookies.
This was needed to save https://wiiki.wii-homebrew.com/Hauptseite and https://breath-of-the-wild.wii-homebrew.com/Hauptseite which are behind cloudflare. I completed the cloudflare challenge in my browser, and then saved the following into a file named `cookies.txt` (where `1698010873` is the expirey time as a unix timestamp - probably it could have been anything, and `longalphanumericstring` was the value seen in firefox's devtools, and the values are separated by tabs, and there was no trailing newline):
```
.wii-homebrew.com	TRUE	/	TRUE	1698010873	cf_clearance	longalphanumericstring
```
Then running with `--cookies cookies.txt` worked properly.  Note that I also changed the user-agent to match what firefox currently …
> Pass requests session to mwclient

- dumpgenerator.py
`title` is already unicode, so we shouldn't need to decode it (and don't in `generateXMLDump`):
https://github.com/WikiTeam/wikiteam/blob/25329be0088b4ece8cc2656f3654e85b5e73a9af/dumpgenerator.py#L777-L785
I ran into this at http://opensimulator.org/wiki/Main_Page, but it didn't occur when I re-ran it so I haven't fully tested this.  Here's the stacktrace from the time it failed though:
```
Downloaded 450 images
Traceback (most recent call last):
File "dumpgenerator.py", line 2573, in <module>
main()
File "dumpgenerator.py", line 2565, in main
createNewDump(config=config, other=other)
File "dumpgenerator.py", line 2144, in createNewDump
session=other['session'])
File "dumpgenerator.py", line 1532, in generateImageDump
text=u'The page "%s" was missing in the wiki (probably deleted)' % …
```
> Fix crash when the image description is missing for an image containing non-ascii characters

- dumpgenerator.py
Needed for https://geck.bethsoft.com/ (along with cookies.txt containing the `__cf_bm` cookie), or else the site isn't detected as mediawiki at all. This is a bit of a follow-up to #441. I also updated the user-agent (I didn't test if this is actually needed, but there's no real harm in using a modern Firefox UA).
> Use the same requests session for getting the wiki engine and checking API/index

- dumpgenerator.py
This was sufficient to dump https://urbanculture.lol/ (which disables Special:Export and the allrevisions API, but supports prop=revisions). The commented out rvlimit line prevented getting more than 1 revision (`continue` wasn't present at all), while `prequest['continue']` failed because iterating over an `OrderedDict` (or a regular `dict`) iterates over the keys, and the variable that needs to be used is `pparams`, not `params` (which does not exist).
There's still a lot of jank with this path that will likely be found via other wikis. It's also jank that there's no way to directly specify this path, and instead it's only accessed via trying to use allrevisions (via `--xmlrevisions`) and that failing.
> Fix exporting via prop=revisions

- dumpgenerator.py
Fix empty .desc files caused by special characters such as `=` or `&` in the title.
See also: https://github.com/mediawiki-client-tools/wikiteam3/issues/75
> Quote `title` to get correct file description

- dumpgenerator.py
MediaWiki 1.36 HTML uses single quotes, as seen in https://wiki.othing.xyz
See also: https://github.com/elsiehupp/wikiteam3/pull/54
> Match single quotes too when scraping namespaces

- dumpgenerator.py
Use `set` instead of `list` to speed up the scanning of large numbers of files (>10000) in `images/`.
---
Benchmark: (one million files in `images/` dir)
```
Set: one million files/s
List: 40 files/s
```
> Speed up file scanning in `images/` dir

- dumpgenerator.py
This affected [OSDev Wiki](https://wiki.osdev.org/Special:AllPages) (which lacks an api.php), where after doing the 4 normal pages of Special:AllPages, it would attempt `What_do_I_need_to_know_about_SMM-Zig_Bare_Bones"  title="This is a special page, you cannot edit the page itself` and then `What_do_I_need_to_know_about_SMM-Zig_Bare_Bones%22++title%3D%22This+is+a+special+page%2C+you+cannot+edit+the+page+itself"  title="This is a special page, you cannot edit the page itself`, repeating in an infinite loop. These URLs came from the "Special page" tab (which has that title text). The fix is to stop at quotes, meaning the regex won't match.  Quotes in actual URLs will be URL-encoded as `%22` so the regex won't interfere with those (see …
> Fix infinite loop on page title scraper

- dumpgenerator.py
Addresses an issue where the `AttributeError: 'module' object has no attribute 'parse'` error occurs in the `generateImageDump` function of the `dumpgenerator.py` file. The error is encountered when running the program using Python 2.
The error arises because the code attempts to import and use the `urllib.parse` module, which is only available in Python 3.
To resolve the issue, the code has been modified to import the correct module based on the Python version being used. The try-except block has been updated to import the `urlparse` function from the `urlparse` module in Python 2 and from the `urllib.parse` module in Python 3.
As this program is designed for Python 2 and can't be operated on Python 3 even with `2to3`, I think using Python 3 libraries is not needed.
> Fix wrong urllib module call in Python 2
