- dumpgenerator.py
- wikiadownloader.py
I'm glad you all have merged my code over. I didn't make the pull request myself because I was still testing the new code on some big wikis and wanted to make sure it was solid before others started using it.
I'm still testing but I've found one bug and you are going to want to merge in my commit in f85b4a3. The bug is small but it is caused by the way that the new code handled missing pages. You can read the commit message for more detail but the old code caused extraneous </page> tags to be added  (easy enough to remove with `grep -v -e '^</page>`) and the log file *not* to be updated.
Also, the wikiadownloader.py was completely broken and the second commit fixes it so that it actually usable.
> fix bug with exception handling

- dumpgenerator.py
Fixes some wikis mentioned in #26, such as http://wiki.toplist.cz/api.php
> Try using URL without index.php as index

- dumpgenerator.py
> Follow API redirects

- dumpgenerator.py
- testing/test_dumpgenerator.py
Fixes http://www.libreidea.org/w/index.php
> Strip ZWNBSP (U+FEFF) Byte-Order Mark from JSON/XML

- requirements.txt
- uploader.py
Remove curl stuff and replace with internetarchive pip package (or https://github.com/jjjake/ia-wrapper) API
> Port uploader.py to use internetarchive package

- uploader.py
This makes it show upload progress.
> Set verbose=True for upload

- dumpgenerator.py
> Normalize path/foo/ to path/foo, so -2, etc. work (fixes #244)

- uploader.py
> Save and upload logos in uploader.py

- dumpgenerator.py
Avoids the two crashes detailed in https://github.com/WikiTeam/wikiteam/issues/8#issuecomment-150160254 .
There's still more to do. Still having some weird issues with certain very large pages, but these are two quick, easy fixes that help fix some crashes.
> Avoid out-of-memory error in two extra places

- listsofwikis/dokuwiki/dokuinstall.txt
> Updated with vancouver.hackspace.ca domain change

- listsofwikis/dokuwiki/dokuinstall.txt
New PR with rebase for latest version
> Updated with vancouver.hackspace.ca -> vanhack.ca domain change

- dumpgenerator.py
Handles limit of 50, continuation in 1.19, HTTPS-only wikis.
> Make --xmlrevisions work on some more wikis

- dumpgenerator.py
- uploader.py
> uploader.py logo and metadata improvements

- uploader.py
Fixes https://github.com/WikiTeam/wikiteam/issues/376
> uploader.py: Handle protocol-relative base URL

- dumpgenerator.py
- launcher.py
The last patches used to complete the Wikia dump of February 2020:
https://archive.org/download/wikia_dump_20200214
> More efficient Wikia download and launcher.py

- dumpgenerator.py
https://github.com/WikiTeam/wikiteam/blob/9d614cf8ad9fe4444b6877743d358f42af27558e/dumpgenerator.py#L1680
default: `args.retries` = 5
> make `requests.session` to use `--retries` value

- uploader.py
> Fix a small syntax error in uploader.py

- dumpgenerator.py
This was probably a copy/paste typo. I don't remember if I ever ran into this in practice but it is something I noticed in the past and never submitted a fix for.
> Fix broken http_method fallback

- dumpgenerator.py
> Fix typo preventing --failfast to apply

- dumpgenerator.py
see: https://github.com/mediawiki-client-tools/mediawiki-scraper/pull/57
code not tested on py2.
> Adjust XML format
